px4_internal_ctrl_extra_params:
  gain:
    # kvxy_extra: 0.0
    # kvz_extra: 0.0
    # kaxy_extra:  0.0
    # kaz_extra: 0.0
    kvxy_extra: 1.5
    kvz_extra: 1.0
    kaxy_extra:  1.0
    kaz_extra: 0.0
linear_controller:
  gain:
    Kpxy: 4
    Kpz: 1.5
    Kvxy: 0.5
    Kvz: 1.5
    Kaxy: 0.5
    Kaz: 1.0
  max_tile_deg: 25 # deg
hover_thrust_ekf:
  init_hover_thrust: 0.25 # 不确定请设置为0.1
  hover_thrust_max: 0.5
  hover_thrust_noise: 0.1
  process_noise: 0.1 #
atti_controller:
  gain:
    Kx: 1.5
    Ky: 1.5
    Kz: 1.5