control_mode: vel
gain:
  Kv0: 1.5
  Kv1: 1.5
  Kv2: 1.5
vel_control_mode:
  # world frame 
  max_xy_vel: 1.0
  max_z_vel: 1.0
rate_ctrl_mode:
  max_pitch_rate: 5 #rad/s
  max_roll_rate: 5 #rad/s
  max_yaw_rate: 5 #rad/s
rate_atti_mode:
  max_tile: 40 #deg
hover_thrust_ekf:
  init_hover_thrust: 0.2
  hover_thrust_min: 0.1
  hover_thrust_max: 0.6
  hover_thrust_noise: 0.01
  process_noise: 0.0


